### ISSUE TITLE
Refactor IDA fill_function for type searching in Stack Vars

### ISSUE THREAD

**Issue by mahaloz** [angr/binsync#111]
- remove fill_structs with a single fill_struct, for the needed type

**Comment by arizvisa** [comment]
Not sure if I'm understanding correctly, but all struc_t (not tinfo_t) have xrefs that connect everything together. This is that `xref_blk_t` stuff. You can use it with anything that's an id, so if your struct member references another struct that the user created you can follow those into and from each frame (if you're not tracking each `vdloc_t` directly from hexrays anyways).

I think you're referring to tinfo_t, though, and not struc_t. Since there isn't an index for local types you're left extracting it (you can extract the ordinals by processing them or ripping it from their serialized forms), or maintaining the index of them yourself (which you'd likely do with a combination of tracking ordinals and hooks to sync modifications). Maybe this is excessive, though.

To differentiate typeinfo in frames made by the user and typeinfo in structures made by the user, you'll want to be fiddling around with idaapi.get_aflags (AFL_USERTI) for structure member ids and NSUP_TYPEINFO which seems to be able to distinguish typeinfo applied to frame member ids. Technically everything has typeinfo, but AFL_USERTI differentiates between types the user has explicitly added/modified from types that were imported from a library. That way when you traverse you only get the relevant tinfo_t. Hope this helps anyways. :-/

**Comment by mahaloz** [comment]
@arizvisa Yup this is useful information. I was planning on somehow incorporating the Xrefs from IDA, but I'm less happy to use it because that would make this struct lookup decompiler specific. Ideally, we should be able to do this on the BinSync level and not the IDA level.

**Comment by mahaloz** [comment]
closed by #170
