### ISSUE TITLE
Auto-fill Git repo in configuration dialog

### ISSUE THREAD

**Issue by mborgerson** [angr/binsync#189]
Git repo upstream may be determined when repo directory is selected. It would be nice to auto-populate it in the dialog.

**Comment by mahaloz** [comment]
This is actually something broken with how we request information from the user @mborgerson, and I am open to ways to minimize confusion. 

## Background
Here is how the dialog is supposed to work:
You have 3 things `local_path`, `remote_url` and `should_init_remote`. 

If you select a `local_path`, and it is a Git repo, there is no need to enter a `remote_url` at all, since we always grab the remote from that local Git repo now. 

If you enter a `remote_url` at all, we now will clone the repo to the same place the binary is currently living. If you also so happened to put in a `local_path`, we will clone it there.

Finally, `should_init_remote` only works in the case where you entered a `remote_url` that has a Git remote with no `binsync/__root__` branch, in which case we create one and maker sure the remote is Git inited.
